// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  navigation_menu: dynamic(() => import("./NavigationMenu")),
  rich_text: dynamic(() => import("./RichText")),
};
